#
# Software Name: Orange Unified Design System
# SPDX-FileCopyrightText: Copyright (c) Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT license,
# the text of which is available at https://opensource.org/license/MIT/
# or see the "LICENSE" file for more details.
#
# Authors: See CONTRIBUTORS.txt
# Software description: A SwiftUI components library with code examples for Orange Unified Design System
#

# About runners: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
# Runners details: https://github.com/actions/runner-images/tree/main/images/macos

name: Check dead code

# Rules for this GitHub Actions workflow
# - workflow can be triggered manually if needed (workflow_dispatch)
# - use "almost" frozen version of macOS
# - is for all branches except for main as deadcode will be found previously in the flow
# - automatically triggered when pull request is opened and has new commits (synchronize)
# But beware, triggered on commit push, so do not be a push-machine-gun!

on:
  push:
    branches-ignore:
      - main       

  workflow_dispatch: 

  pull_request:
    types:
      - opened
      - synchronize    
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  deadcode:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb # v1.257.0, https://github.com/ruby/setup-ruby
        with:
          ruby-version: '3.3'

      - name: Install Fastlane
        run: |
          bundle install

      - name: Install Periphery
        run: |
          brew install periphery

      - name: Look for dead code
        run: |
          cd DesignToolbox
          bundle exec pod install
          bundle exec fastlane check_dead_code